### PR TITLE
Update versions and a couple of improvements

### PR DESCRIPTION
**Pull request by martindurant**
@TomAugspurger : tested and seems OK.

### CODE REVIEW

**Comment by martindurant** [comment]
Fixes #3 
Fixes #4

**Comment by TomAugspurger** [comment]
LGTM.

**Comment by TomAugspurger** [comment]
FYI, pandas is doing a 0.23.2 release soon, but I don't *think* it'll break anything for the tutorial :)

**Comment by martindurant** [comment]
There is no need to remake the image, so nothing will change.
Each time we make a new image, we should run a full tests to see that things are working. Upstream version changes are worth keeping in mind for those installing locally.

**Pull request merged**
